version: '3'
services:
  web:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  frontend:
    build:
      context: ./react/MiProyecto
    ports:
      - "3000:3000"
      - "19002:19002"   
      - "8081:8081"      
    environment:
      - REACT_APP_API_URL=http://ec2-3-84-62-14.compute-1.amazonaws.com:5000
    depends_on:
      - web
