version: '3'
services:
  web:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  frontend:
    build:
      context: ./react/MiProyecto
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://web:5000
    depends_on:
      - web
